=== AndresMontess/Proyectos/1ASIR/SGI/3_Trimestre/XML/DTD-ejercicio.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD generado por XMLSpy v2023 rel. 2 (x64) (http://www.altova.com/es) -->
<!ELEMENT ROW (cod_paciente, Nombre, Apellido, Apellido2, Localidad, Provincia, Edad, Email, Historia)>
<!ELEMENT DATA (ROW)>
<!ELEMENT Edad (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Apellido (#PCDATA)>
<!ELEMENT Historia (#PCDATA)>
<!ELEMENT Apellido2 (#PCDATA)>
<!ELEMENT Localidad (#PCDATA)>
<!ELEMENT Provincia (#PCDATA)>
<!ELEMENT cod_paciente (#PCDATA)>

=== AndresMontess/Proyectos/SGI/3_Trimestre/XML/DATOS-Alarcon-most.xml
<!DOCTYPE DATA SYSTEM "C:\Users\madrid\Documents\Andres\SGI\3_Trimestre\XML\DTD-ejercicio.dtd">
<?xml-stylesheet type="text/xsl" href="file:///C:/Users/madrid/Documents/Andres/SGI/3_Trimestre/XML/XLS-Ejercicio1.xslt"?>
<DATA>
	<ROW>
		<cod_paciente>08</cod_paciente>
		<Nombre>Alberto</Nombre>
		<Apellido>Fern√°ndez</Apellido>
		<Apellido2>Vargas</Apellido2>
		<Localidad>Mostoles</Localidad>
		<Provincia>Madrid</Provincia>
		<Edad>59</Edad>
		<Email>NULL</Email>
		<Historia>http://historia08.com</Historia>
	</ROW>
</DATA>
